name: Update File

on:
  workflow_dispatch:
  schedule:
  - cron: "17,47 * * * *"

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: python3 -m pip install -r requirements.txt
      - name: Update proxies
        run: python3 main.py
        env:
          FARM_PROXY_API_KEY=${{ secrets.FARM_PROXY_API_KEY }}
          STABLE_IP_PROXY=${{ secrets.STABLE_IP_PROXY }}
      - uses: test-room-7/action-update-file@v1
        with:
          file-path: proxies.txt
          commit-msg: Update proxies
          github-token: ${{ secrets.GITHUB_TOKEN }}
